import { Platform, StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "../../../pixelRatio";
import theme from "../../../common/theme";
import { FontFamily } from "../../../common/AssetUtils";

const styles = StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: theme.theme,
  },
  container: {
    flex: 1,
    backgroundColor: theme.theme,
  },
  appLogoImage: {
    marginTop: verticalScale(50),
    alignSelf: "center",
  },
  optionMainView: {
    borderColor: theme.white,
    borderRadius: moderateScale(30),
    borderWidth: moderateScale(3.5),
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: verticalScale(12),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 8,
    backgroundColor: theme.theme,
    height: verticalScale(48),
  },
  optionTitleText: {
    fontSize: moderateScale(22),
    fontFamily: FontFamily.InriaSansRegular,
    color: theme.white,
    textAlign: "center",
  },
  lineView: {
    height: verticalScale(5),
    backgroundColor: theme.white,
    width: "75%",
    marginTop: verticalScale(15),
    alignSelf: "center",
  },
  textShadow: {
    textShadowColor: "rgba(0, 0, 0, 0.25)",
    textShadowOffset: { width: -2, height: 1 },
    textShadowRadius: 3,
  },
  buttonText: {
    fontSize: moderateScale(22),
    fontFamily: FontFamily.InriaSansRegular,
    color: theme.white,
    textAlign: "center",
  },
  logoutButton: {
    height: verticalScale(50),
    backgroundColor: theme.theme,
    borderWidth: moderateScale(3.5),
    borderColor: theme.white,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: moderateScale(30),
    width: "100%",
    marginTop: verticalScale(10),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 8,
  },
  socialLoginView: {
    backgroundColor: theme.black,
    height: verticalScale(38),
    alignItems: "center",
    flexDirection: "row",
    width: "95%",
    borderRadius: moderateScale(30),
    marginTop: verticalScale(12),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 8,
  },
  socialLoginText: {
    color: theme.white,
    fontFamily: FontFamily.InriaSansRegular,
    fontSize: moderateScale(19),
    textAlign: "center",
    marginStart: moderateScale(25),
  },
  rbsheetContainerStyle: {
    width: "90%",
    alignSelf: "center",
    marginBottom: verticalScale(30),
    borderRadius: moderateScale(18),
    backgroundColor: theme.theme,
    padding: scale(15),
    borderColor: theme.white,
    borderWidth: moderateScale(5),
    justifyContent: "center",
  },
  languageText: {
    color: theme.white,
    fontSize: moderateScale(20),
    fontFamily: FontFamily.InriaSansItalic,
    fontWeight: "500",
    textAlign: "center",
  },
  languageLineView: {
    backgroundColor: theme.white,
    height: StyleSheet.hairlineWidth,
    marginVertical: verticalScale(10),
  },
  checkIcon: {
    height: verticalScale(15),
    width: scale(15),
    tintColor: theme.white,
    position: "absolute",
    right: scale(70),
    marginTop: Platform.OS == "android" ? verticalScale(4) : 0,
  },
  rowContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
});

export default styles;
